Jakarta 91 master
eclipse/microprofile-reactive-messaging pull request #141
Opened 2021-11-24 14:31 UTC by tomas-langer

Related to #137 

Changes for Jakarta packages and MP Parent for `master` branch.

2022-01-05 08:39 UTC, cescoffier approved these changes
Except the formatting change (and the removal of the config), it looks good to me. I'm going to run some tests on our side to see where we stand.

2022-01-05 08:39 UTC, cescoffier commented on api/src/main/java/org/eclipse/microprofile/reactive/messaging/Message.java
> +        } else {
Cosmetic - Any reason to change the format?

2022-01-05 10:23 UTC, cescoffier commented
Building the branch seems to update the format of almost every single file.

2022-01-05 11:14 UTC, radcortez commented
> Building the branch seems to update the format of almost every single file.

Yes, the parent pom now applies a consistent code style to every MP project. Before it was per project.

2022-01-05 11:32 UTC, Emily-Jiang commented on api/src/main/java/org/eclipse/microprofile/reactive/messaging/package-info.java
> +@org.osgi.annotation.versioning.Version("3.0")
The new version should be 2.0 not 3.0. Every package version should tell whether there are changes in a release. This version is not the version of spec.

2022-01-05 11:33 UTC, Emily-Jiang commented on api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/package-info.java
> +@org.osgi.annotation.versioning.Version("3.0")
```suggestion
@org.osgi.annotation.versioning.Version("2.0")
```

2022-01-05 11:33 UTC, Emily-Jiang commented on api/src/main/java/org/eclipse/microprofile/reactive/messaging/package-info.java
> +@org.osgi.annotation.versioning.Version("3.0")
```suggestion
@org.osgi.annotation.versioning.Version("2.0")
```

2022-01-05 11:34 UTC, Emily-Jiang commented on pom.xml
> +        <version>2.1</version>
```suggestion
        <version>2.3</version>
```

2022-01-05 11:36 UTC, Emily-Jiang commented on pom.xml
> +        <cdi-api.version>3.0</cdi-api.version>
```suggestion
```

2022-01-05 11:41 UTC, Emily-Jiang commented on pom.xml
> -            </dependency>
The section `<build>` should not be necessary. Please just get rid of them as the parent pom.xml has them.

2022-01-05 11:47 UTC, Emily-Jiang commented on tck/pom.xml
> +        <version>3.0-SNAPSHOT</version>
The arquillian dependency management is incorrect. The correct version has been specified in the parent pom.xml. You just need to declare the dependency on the api and remove the line 35 and 39-40

2022-01-05 11:50 UTC, Emily-Jiang requested changes
See the inline comments. Also the spec needs to have a release note to document the changes in 2.0.

2022-01-05 11:57 UTC, Emily-Jiang commented
A marker file Tck needs to be added to the tck folder. See an example [here](https://github.com/eclipse/microprofile-fault-tolerance/tree/master/tck/src/main/resources/META-INF)

2022-01-05 12:13 UTC, Emily-Jiang commented
Step 4, 5 and 6 needs be done in [this](https://docs.google.com/document/d/1bhhfmhxHJpQdmdUtQw5o_WtScpzkfHoTNGPvrQnGhc0/edit#) doc.

2022-02-07 14:42 UTC, Emily-Jiang approved these changes
LGTM!

2022-02-07 14:45 UTC, merged